# source: https://github.com/nezhar/wordpress-docker-compose/blob/master/docker-compose.yml

services:
  wordpress:
    build:
      context: .
    ports:
      - 8080:80
    volumes:
      - wp-html:/var/www/html
      - ./themes/:/var/www/html/wp-content/themes
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    depends_on:
      - db

  db:
    image: mariadb:10.6.4-focal
    ports:
      - 3306:3306
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: somewordpress

volumes:
  db_data:
  wp-html:
